/*
 * Builds the dot-matrix map of Australia used in the Coverage section.
 * Samples a regular grid over the country outline (world-atlas, Natural Earth
 * 50m) and keeps the points that fall on land. Output is plain data, so the
 * page ships no map library.
 *
 * Run: node scripts/map.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoContains } from "d3-geo";

const topo = JSON.parse(readFileSync("node_modules/world-atlas/countries-50m.json", "utf8"));
const aus = feature(topo, topo.objects.countries).features.find((f) => f.id === "036");

// Mainland + Tasmania only: clip to a box that drops the external territories.
const W = 1000, H = 900, STEP = 13;
const projection = geoMercator().fitExtent([[10, 10], [W - 10, H - 10]], {
  type: "Polygon",
  coordinates: [[[112.5, -10.5], [154, -10.5], [154, -44], [112.5, -44], [112.5, -10.5]]],
});

const dots = [];
for (let y = STEP / 2; y < H; y += STEP) {
  for (let x = STEP / 2; x < W; x += STEP) {
    const ll = projection.invert([x, y]);
    if (ll[0] < 112.5 || ll[0] > 154 || ll[1] < -44 || ll[1] > -10.5) continue;
    if (geoContains(aus, ll)) dots.push([Math.round(x), Math.round(y)]);
  }
}

const cities = [
  ["Melbourne", 144.96, -37.81, true],
  ["Sydney", 151.21, -33.87],
  ["Canberra", 149.13, -35.28],
  ["Brisbane", 153.03, -27.47],
  ["Adelaide", 138.6, -34.93],
  ["Perth", 115.86, -31.95],
  ["Hobart", 147.33, -42.88],
  ["Darwin", 130.84, -12.46],
].map(([name, lon, lat, hq]) => {
  const [x, y] = projection([lon, lat]);
  return { name, x: Math.round(x), y: Math.round(y), lat, lon, hq: !!hq };
});

writeFileSync(
  "src/content/map.ts",
  `// Generated by scripts/map.mjs — do not edit by hand.\nexport const MAP = { w: ${W}, h: ${H}, step: ${STEP} };\nexport const DOTS: [number, number][] = ${JSON.stringify(dots)};\nexport const CITIES = ${JSON.stringify(cities, null, 2)};\n`,
);
console.log(dots.length, "dots");
